name: Lint Markdown
on:
  pull_request:
    branches: [ "main" ]

jobs:
  prose-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install prose-lint
        run: npm install -g prose-lint

      - name: Lint all .md files
        run: |
          find . -name "*.md" -exec prose-lint {} \;
